# Generated by Django 2.2.16 on 2022-12-22 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientsamount',
            name='name',
        ),
        migrations.AddField(
            model_name='ingredientsamount',
            name='ingredients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='foods.Ingredient', verbose_name='Связанные ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', through='foods.IngredientsAmount', to='foods.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
