# Generated by Django 2.2.16 on 2022-12-22 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20221222_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsamount',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='foods.Ingredient', verbose_name='Связанные ингредиенты'),
        ),
    ]
